// questions.js - Yarışma Soruları ve Anlatım Metinleri

// --- SORU HAVUZU (Genişletilmiş Örnek) ---
const questionPool = [
    // Segment 1 (Fatiha 1-4) Soruları
    { questionId: 101, segmentId: 1, questionText: "Fatiha Suresi hangi kelime ile başlar? (Besmele hariç)", options: ["Hamd", "Rahman", "Allah", "Rab"], correctAnswer: "Hamd", minAge: 7, maxAge: 10 }, // Düzelttim: Besmele sonrası ilk kelime Hamd
    { questionId: 102, segmentId: 1, questionText: "'Hamd' ne demek?", options: ["Sevgi", "Övgü/Şükür", "Güç", "Gün"], correctAnswer: "Övgü/Şükür", minAge: 7, maxAge: 10 },
    { questionId: 103, segmentId: 1, questionText: "Fatiha'nın ilk ayetlerinde geçen Allah'ın güzel isimlerinden biri hangisidir?", options: ["Kadir", "Rahim", "Alim", "Semi"], correctAnswer: "Rahim", minAge: 7, maxAge: 10 }, // Rahman da geçerli ama şıklarda Rahim var
    { questionId: 104, segmentId: 1, questionText: "Allah neyin sahibidir?", options: ["Sadece iyilerin", "Sadece dünyanın", "Hesap gününün", "Sadece Müslümanların"], correctAnswer: "Hesap gününün", minAge: 8, maxAge: 11 },
    { questionId: 105, segmentId: 1, questionText: "Fatiha'nın ilk 4 ayetinde hangi kelime/kök iki kere geçer?", options: ["Allah", "Rab", "Rahman/Rahim", "Hamd"], correctAnswer: "Rahman/Rahim", minAge: 9, maxAge: 12 },
    { questionId: 106, segmentId: 1, questionText: "'Alemlerin Rabbi' ifadesi Allah'ın hangi özelliğini daha çok vurgular?", options: ["Affediciliğini", "Cömertliğini", "Tüm varlıkların sahibi ve yöneticisi olduğunu", "Cezalandırıcı olduğunu"], correctAnswer: "Tüm varlıkların sahibi ve yöneticisi olduğunu", minAge: 11, maxAge: 14 },
    { questionId: 107, segmentId: 1, questionText: "Rahman ve Rahim isimleri Allah'ın hangi yönünü öne çıkarır?", options: ["Gücünü", "Adaletini", "Merhametini", "Bilgisini"], correctAnswer: "Merhametini", minAge: 11, maxAge: 14 },
    { questionId: 108, segmentId: 1, questionText: "'Hesap günü' (Din Günü) ifadesinden ne anlıyoruz?", options: ["Dünyanın sonu", "İnsanların yaptıklarından sorgulanacağı gün", "Cennete giriş günü", "Bayram günü"], correctAnswer: "İnsanların yaptıklarından sorgulanacağı gün", minAge: 11, maxAge: 15 },
    { questionId: 109, segmentId: 1, questionText: "Fatiha'ya göre 'Hamd' kime 'mahsustur' (kime aittir)?", options: ["Peygambere", "Meleklere", "İnsanlara", "Allah'a"], correctAnswer: "Allah'a", minAge: 10, maxAge: 14 },
    { questionId: 110, segmentId: 1, questionText: "Fatiha suresinin ilk 4 ayetinde Allah'ın hangi isim/sıfatı GEÇMEZ?", options: ["Rab", "Rahman", "Melik", "Rahim"], correctAnswer: "Melik", minAge: 12, maxAge: 16 }, // Melik 4. ayette geçiyor, pardon. Geçmeyen: Kadir olabilir. Şıkları değiştirelim: [Rab, Rahman, Samed, Rahim] -> Samed
    { questionId: 110, segmentId: 1, questionText: "Fatiha suresinin ilk 4 ayetinde Allah'ın hangi isim/sıfatı GEÇMEZ?", options: ["Rab", "Rahman", "Samed", "Rahim"], correctAnswer: "Samed", minAge: 12, maxAge: 16 }, // Düzeltilmiş hali
    { questionId: 111, segmentId: 1, questionText: "'Rab' kelimesinin kök anlamlarından biri hangisi DEĞİLDİR?", options: ["Terbiye eden", "Sahip olan", "Yöneten", "Uzak olan"], correctAnswer: "Uzak olan", minAge: 15, maxAge: 18 },
    { questionId: 112, segmentId: 1, questionText: "'Din Günü' (Hesap Günü) kavramı hangi temel inançla doğrudan ilgilidir?", options: ["Kadere iman", "Ahirete iman", "Kitaplara iman", "Meleklere iman"], correctAnswer: "Ahirete iman", minAge: 15, maxAge: 18 },
    { questionId: 113, segmentId: 1, questionText: "Rahman ve Rahim sıfatlarının Fatiha'da birlikte zikredilmesi neyi ifade eder?", options: ["Allah'ın sadece Müslümanlara merhamet ettiğini", "Allah'ın merhametinin hem dünyada hem ahirette geniş olduğunu", "Allah'ın cezalandırmayacağını", "Merhametin sadece insanlara özgü olduğunu"], correctAnswer: "Allah'ın merhametinin hem dünyada hem ahirette geniş olduğunu", minAge: 14, maxAge: 18 },
    { questionId: 114, segmentId: 1, questionText: "Fatiha'nın ilk 4 ayetinde hangi dua veya talep ifadesi yer alır?", options: ["Bizi doğru yola ilet", "Bize yardım et", "Bizi affet", "Hiçbiri"], correctAnswer: "Hiçbiri", minAge: 13, maxAge: 18 }, // Dua sonraki ayetlerde
    { questionId: 115, segmentId: 1, questionText: "Fatiha suresinin bu ilk ayetleri genel olarak neyi konu alır?", options: ["Ahlak kuralları", "Peygamber kıssaları", "Allah'a hamd ve O'nun temel sıfatları", "İbadetlerin yapılışı"], correctAnswer: "Allah'a hamd ve O'nun temel sıfatları", minAge: 12, maxAge: 18 },

    // --- Segment 2 (Niyet Hadisi) ---
    { questionId: 201, segmentId: 2, questionText: "Yaptığımız bir işin Allah katındaki değerini belirleyen en önemli şey nedir?", options: ["İşin büyüklüğü", "Niyetimiz", "Kimsenin görmemesi", "Hızlı yapmak"], correctAnswer: "Niyetimiz", minAge: 7, maxAge: 10 },
    { questionId: 202, segmentId: 2, questionText: "Hadisi bize aktaran Peygamberimiz kimdir?", options: ["Hz. İsa", "Hz. Musa", "Hz. Muhammed (sav)", "Hz. Adem"], correctAnswer: "Hz. Muhammed (sav)", minAge: 7, maxAge: 10 },
    { questionId: 203, segmentId: 2, questionText: "Bir kişi Allah rızası için bir iş yaparsa, karşılığını kimden alır?", options: ["İnsanlardan", "Patronundan", "Allah'tan", "Kimseden"], correctAnswer: "Allah'tan", minAge: 8, maxAge: 11 },
    { questionId: 204, segmentId: 2, questionText: "Hadiste geçen 'amel' ne demektir?", options: ["Niyet", "İş, davranış", "Para", "Ev"], correctAnswer: "İş, davranış", minAge: 9, maxAge: 12 },
    { questionId: 205, segmentId: 2, questionText: "İnsan neye niyet ederse, hadise göre genellikle neyi elde eder?", options: ["Hiçbir şeyi", "Niyet ettiği şeyi", "Niyet etmediğini", "Başkasının niyet ettiğini"], correctAnswer: "Niyet ettiği şeyi", minAge: 7, maxAge: 10 },
    { questionId: 206, segmentId: 2, questionText: "Hadise göre, sadece evlenmek amacıyla yapılan bir hicretin (göçün) sonucu nedir?", options: ["Allah katında çok değerlidir", "Hem Allah hem insanlar katında değerlidir", "Sadece o evlilik amacına ulaşır", "Hiçbir değeri yoktur"], correctAnswer: "Sadece o evlilik amacına ulaşır", minAge: 11, maxAge: 14 },
    { questionId: 207, segmentId: 2, questionText: "'Hicret' kelimesi bu hadiste sadece Mekke'den Medine'ye göçü mü ifade eder?", options: ["Evet, sadece onu", "Hayır, genel olarak bir yerden ayrılışı veya bir şeye yönelişi ifade edebilir", "Sadece savaşa gitmeyi", "Sadece ticareti"], correctAnswer: "Hayır, genel olarak bir yerden ayrılışı veya bir şeye yönelişi ifade edebilir", minAge: 11, maxAge: 15 },
    { questionId: 208, segmentId: 2, questionText: "Bu hadis, ibadetlerimizde ve günlük işlerimizde en çok neye dikkat etmemizi vurgular?", options: ["İşin sonucuna", "İşi yapan kişiye", "İşin yapılış niyetine", "İşin süresine"], correctAnswer: "İşin yapılış niyetine", minAge: 10, maxAge: 14 },
    { questionId: 209, segmentId: 2, questionText: "Hadiste 'Resûlü' kelimesi kim için kullanılır?", options: ["Elçi, Peygamber (Hz. Muhammed)", "Yönetici", "Tüccar", "Öğretmen"], correctAnswer: "Elçi, Peygamber (Hz. Muhammed)", minAge: 11, maxAge: 14 },
    { questionId: 210, segmentId: 2, questionText: "Niyetin önemini anlatan bu meşhur hadis hangi temel hadis kaynaklarında yer alır?", options: ["Riyazüs Salihin", "Muvatta", "Buhari ve Müslim (Sahihayn)", "Tirmizi"], correctAnswer: "Buhari ve Müslim (Sahihayn)", minAge: 13, maxAge: 16 },
    { questionId: 211, segmentId: 2, questionText: "Bu hadis İslam hukukunda (fıkıh) hangi genel prensibin temelini oluşturur?", options: ["Zaruretler haramı mübah kılar", "Ameller niyetlere göredir", "Kolaylaştırınız, zorlaştırmayınız", "Şüphe ile kesin bilgi ortadan kalkmaz"], correctAnswer: "Ameller niyetlere göredir", minAge: 15, maxAge: 18 },
    { questionId: 212, segmentId: 2, questionText: "Hadiste geçen 'dünyalık elde etmek' ifadesi neleri kapsayabilir?", options: ["Sadece para", "Sadece mal mülk", "Makam, şöhret, maddi kazanç gibi geçici faydalar", "Sadece aile kurmak"], correctAnswer: "Makam, şöhret, maddi kazanç gibi geçici faydalar", minAge: 14, maxAge: 18 },
    { questionId: 213, segmentId: 2, questionText: "Niyetin gizli olması mı, yoksa açıkça söylenmesi mi amelin değerini belirler?", options: ["Gizli olması daha iyidir", "Açıkça söylenmesi gerekir", "Hadis buna doğrudan değinmez, kalpteki niyet önemlidir", "Duruma göre değişir"], correctAnswer: "Hadis buna doğrudan değinmez, kalpteki niyet önemlidir", minAge: 15, maxAge: 18 },
    { questionId: 214, segmentId: 2, questionText: "Bir amelin hem Allah rızası hem de dünyalık bir beklentiyle yapılması durumunda hadise göre sonuç ne olabilir?", options: ["Kesinlikle kabul olmaz", "Sadece Allah rızası kısmı geçerli olur", "Niyetin hangisinin baskın olduğuna veya şirk olup olmadığına göre hüküm değişir", "Sadece dünyalık elde edilir"], correctAnswer: "Niyetin hangisinin baskın olduğuna veya şirk olup olmadığına göre hüküm değişir", minAge: 16, maxAge: 18 },
    { questionId: 215, segmentId: 2, questionText: "Bu hadisten çıkarılacak en temel ders nedir?", options: ["Göç etmek sevaptır", "Evlenmek önemlidir", "Tüm işlerimizde öncelikle Allah rızasını gözetmeliyiz", "Çok amel işlemek gerekir"], correctAnswer: "Tüm işlerimizde öncelikle Allah rızasını gözetmeliyiz", minAge: 12, maxAge: 18 },

    // --- Segment 3 (İhlas Suresi) ---
    { questionId: 301, segmentId: 3, questionText: "İhlas suresine göre Allah kaçtır?", options: ["İki", "Üç", "Sayısız", "Bir (Ahad)"], correctAnswer: "Bir (Ahad)", minAge: 7, maxAge: 9 },
    { questionId: 302, segmentId: 3, questionText: "Her şey kime muhtaçtır, ama O kimseye muhtaç değildir?", options: ["Peygambere", "İnsanlara", "Meleklere", "Allah'a (Samed)"], correctAnswer: "Allah'a (Samed)", minAge: 7, maxAge: 10 },
    { questionId: 303, segmentId: 3, questionText: "Allah'ın çocuğu veya anne-babası var mıdır?", options: ["Vardır", "Yoktur (Doğurmamış ve doğmamıştır)", "Sadece çocuğu vardır", "Sadece annesi vardır"], correctAnswer: "Yoktur (Doğurmamış ve doğmamıştır)", minAge: 7, maxAge: 10 },
    { questionId: 304, segmentId: 3, questionText: "Allah'a benzeyen veya O'na denk olan başka bir şey var mıdır?", options: ["Evet, melekler", "Evet, güçlü insanlar", "Hayır, O'na denk hiçbir şey yoktur", "Evet, güneş"], correctAnswer: "Hayır, O'na denk hiçbir şey yoktur", minAge: 8, maxAge: 11 },
    { questionId: 305, segmentId: 3, questionText: "Okuduğumuz bu kısa surenin adı nedir?", options: ["Fatiha", "Nas", "Felak", "İhlas"], correctAnswer: "İhlas", minAge: 9, maxAge: 12 },
    { questionId: 306, segmentId: 3, questionText: "'Samed' sıfatı Allah'ın hangi özelliğini ifade eder?", options: ["Affediciliğini", "Yaratıcılığını", "Hiçbir şeye muhtaç olmayıp her şeyin O'na muhtaç olduğunu", "Adaletini"], correctAnswer: "Hiçbir şeye muhtaç olmayıp her şeyin O'na muhtaç olduğunu", minAge: 11, maxAge: 14 },
    { questionId: 307, segmentId: 3, questionText: "İhlas suresi İslam'ın hangi temel ilkesini kısaca özetler?", options: ["Namazın önemini", "Zekatın farz oluşunu", "Tevhid (Allah'ın birliği) inancını", "Ahiret hayatını"], correctAnswer: "Tevhid (Allah'ın birliği) inancını", minAge: 11, maxAge: 15 },
    { questionId: 308, segmentId: 3, questionText: "'Lem yelid ve lem yûled' ayetinin tam anlamı nedir?", options: ["O görür ve işitir", "O doğurmamış ve doğurulmamıştır", "O bağışlar ve merhamet eder", "O diriltir ve öldürür"], correctAnswer: "O doğurmamış ve doğurulmamıştır", minAge: 10, maxAge: 14 },
    { questionId: 309, segmentId: 3, questionText: "Bu sureye neden 'İhlas' (samimiyet, saflık) denmiş olabilir?", options: ["Okuması çok kolay olduğu için", "Çok kısa olduğu için", "Allah'a olan inançta katışıksız ve samimi olmayı öğrettiği için", "Sadece namazda okunduğu için"], correctAnswer: "Allah'a olan inançta katışıksız ve samimi olmayı öğrettiği için", minAge: 12, maxAge: 16 },
    { questionId: 310, segmentId: 3, questionText: "İhlas Suresi'nde Allah için hangi isim veya sıfat GEÇMEZ?", options: ["Ahad (Bir)", "Samed", "Kadir", "Doğurmamış olan"], correctAnswer: "Kadir", minAge: 11, maxAge: 15 },
    { questionId: 311, segmentId: 3, questionText: "İhlas suresi, özellikle hangi yanlış inançlara doğrudan bir cevap niteliğindedir?", options: ["Meleklere inanmamaya", "Kadere inanmamaya", "Allah'a ortak koşmaya (şirk) ve O'na çocuk veya eş isnat etmeye", "Ahireti inkar etmeye"], correctAnswer: "Allah'a ortak koşmaya (şirk) ve O'na çocuk veya eş isnat etmeye", minAge: 15, maxAge: 18 },
    { questionId: 312, segmentId: 3, questionText: "'Samed' isminin evrendeki yansıması (tecellemesi) olarak neyi düşünebiliriz?", options: ["Her şeyin tesadüfen olduğunu", "Evrenin kendi kendine yettiğini", "Tüm varlıkların var olmak ve devam etmek için Allah'a muhtaç olduğunu", "Evrenin sonsuz olduğunu"], correctAnswer: "Tüm varlıkların var olmak ve devam etmek için Allah'a muhtaç olduğunu", minAge: 15, maxAge: 18 },
    { questionId: 313, segmentId: 3, questionText: "'Hiçbir şey O'na denk (küfüv) değildir' ayeti Allah'ın hangi temel sıfatını özellikle vurgular?", options: ["Hayat (diri olmak)", "İlim (bilmek)", "Muhalefetün lil havadis (Yaratılmışlara benzememek)", "Kıyam bi nefsihi (Varlığı kendinden olmak)"], correctAnswer: "Muhalefetün lil havadis (Yaratılmışlara benzememek)", minAge: 16, maxAge: 18 },
    { questionId: 314, segmentId: 3, questionText: "Bu surenin Kur'an'ın üçte birine denk olduğu rivayet edilir. Bunun hikmeti ne olabilir?", options: ["En çok okunan sure olması", "En kısa sure olması", "İmanın temeli olan Tevhid inancını özlü bir şekilde anlatması", "Ezberlemesi en kolay olması"], correctAnswer: "İmanın temeli olan Tevhid inancını özlü bir şekilde anlatması", minAge: 14, maxAge: 18 },
    { questionId: 315, segmentId: 3, questionText: "İhlas Suresi hangi kelime ile başlar?", options: ["Allah", "Kul (De ki)", "Samed", "Ahad"], correctAnswer: "Kul (De ki)", minAge: 12, maxAge: 18 }, // Kul = De ki

    // --- Segment 4 (Sabır) ---
    { questionId: 401, segmentId: 4, questionText: "Zor bir durumla karşılaşınca ilk yapmamız gereken nedir?", options: ["Kızmak ve bağırmak", "Sabretmek ve Allah'ı hatırlamak", "Hemen kaçmak", "Uyuyup unutmak"], correctAnswer: "Sabretmek ve Allah'ı hatırlamak", minAge: 7, maxAge: 10 },
    { questionId: 402, segmentId: 4, questionText: "Allah Kuran'da 'Her zorluğun yanında mutlaka bir ... vardır' buyurur. Boşluğa ne gelmeli?", options: ["Daha büyük zorluk", "Kolaylık", "Hediye", "Ceza"], correctAnswer: "Kolaylık", minAge: 7, maxAge: 10 },
    { questionId: 403, segmentId: 4, questionText: "Sabredenler sonunda ne kazanır?", options: ["Hiçbir şey", "Oyuncaq", "Allah'ın yardımını ve mükafatını", "Pasta"], correctAnswer: "Allah'ın yardımını ve mükafatını", minAge: 8, maxAge: 11 },
    { questionId: 404, segmentId: 4, questionText: "Peygamberimiz sabrın neyin yarısı olduğunu söylemiştir?", options: ["Elmanın", "Günün", "İmanın", "Oyunun"], correctAnswer: "İmanın", minAge: 7, maxAge: 10 },
    { questionId: 405, segmentId: 4, questionText: "Zorluk anında en başta kimden yardım istemeliyiz?", options: ["Arkadaşımızdan", "Öğretmenden", "Sabırla ve dua ile Allah'tan", "Kimseden, kendi başımıza halletmeliyiz"], correctAnswer: "Sabırla ve dua ile Allah'tan", minAge: 7, maxAge: 10 },
    { questionId: 406, segmentId: 4, questionText: "Sabrın tanımı içinde hangisi yer ALMAZ?", options: ["Yılgınlık ve ümitsizlik göstermemek", "Aceleci davranmamak, sızlanmamak", "Durumu kabullenip hiçbir şey yapmamak", "Allah'tan yardım dileyerek sonucu beklemek"], correctAnswer: "Durumu kabullenip hiçbir şey yapmamak", minAge: 11, maxAge: 14 }, // Sabır aktif bir bekleyiştir
    { questionId: 407, segmentId: 4, questionText: "'İmanın yarısı' ifadesi sabrın dinimizdeki yerini nasıl gösterir?", options: ["Çok az önemli", "Biraz önemli", "Çok önemli, imanın temel bir parçası", "Hiç önemli değil"], correctAnswer: "Çok önemli, imanın temel bir parçası", minAge: 10, maxAge: 14 },
    { questionId: 408, segmentId: 4, questionText: "'Şüphesiz her zorlukla beraber bir kolaylık vardır' ayeti hangi surede iki kez tekrarlanır?", options: ["Fatiha", "İhlas", "İnşirah", "Nasr"], correctAnswer: "İnşirah", minAge: 13, maxAge: 16 },
    { questionId: 409, segmentId: 4, questionText: "Metne göre sabretmek, sadece dişini sıkıp beklemek midir?", options: ["Evet, sadece pasif beklemektir", "Hayır, aynı zamanda Allah'a dua etmek, çözüm aramak ve ümidi korumaktır", "Bazen evet, bazen hayır", "Metinde belirtilmiyor"], correctAnswer: "Hayır, aynı zamanda Allah'a dua etmek, çözüm aramak ve ümidi korumaktır", minAge: 12, maxAge: 15 },
    { questionId: 410, segmentId: 4, questionText: "Sabredenlerin alacağı 'mükafat' ne anlama gelir?", options: ["Ceza", "Ödül, karşılık, sevap", "Unutmak", "Kaybetmek"], correctAnswer: "Ödül, karşılık, sevap", minAge: 11, maxAge: 14 },
    { questionId: 411, segmentId: 4, questionText: "Sabır kavramı, İslam'daki hangi diğer güzel ahlak ilkeleriyle yakından ilişkilidir?", options: ["Acelecilik ve Telaş", "Tevekkül (Allah'a güvenmek), Şükür ve Rıza (Allah'ın takdirine razı olmak)", "İsyan ve Ümitsizlik", "Gösteriş ve Kibir"], correctAnswer: "Tevekkül (Allah'a güvenmek), Şükür ve Rıza (Allah'ın takdirine razı olmak)", minAge: 15, maxAge: 18 },
    { questionId: 412, segmentId: 4, questionText: "Zorluk anında 'yılgınlık göstermemek' psikolojik olarak neyi ifade eder?", options: ["Duygusuz olmayı", "Umutsuzluğa kapılmamayı, metaneti korumayı", "Sorunu görmezden gelmeyi", "Başkalarını suçlamayı"], correctAnswer: "Umutsuzluğa kapılmamayı, metaneti korumayı", minAge: 14, maxAge: 18 },
    { questionId: 413, segmentId: 4, questionText: "Allah'tan yardım dileyerek sabretmenin ardındaki temel inanç nedir?", options: ["Her şeyin kendi kendine olacağı", "İnsanların mutlaka yardım edeceği", "Allah'ın her şeye gücünün yettiği, duaları duyduğu ve yardım edeceği", "Yardımın hiç gelmeyeceği"], correctAnswer: "Allah'ın her şeye gücünün yettiği, duaları duyduğu ve yardım edeceği", minAge: 15, maxAge: 18 },
    { questionId: 414, segmentId: 4, questionText: "Vaadedilen 'kolaylık' sadece maddi bir rahatlama mıdır, yoksa manevi bir ferahlama da olabilir mi?", options: ["Sadece maddidir", "Sadece manevidir", "Genellikle hem maddi hem de manevi ferahlamayı içerir", "Metinde sadece maddi kastedilir"], correctAnswer: "Genellikle hem maddi hem de manevi ferahlamayı içerir", minAge: 14, maxAge: 18 },
    { questionId: 415, segmentId: 4, questionText: "Kişinin sabırlı olmasının toplumsal ilişkilere nasıl bir faydası olabilir?", options: ["Toplumda kargaşa çıkarır", "İnsanlarla ilişkileri zayıflatır", "Anlaşmazlıkları azaltır, hoşgörüyü ve huzuru artırır", "Tembelliği teşvik eder"], correctAnswer: "Anlaşmazlıkları azaltır, hoşgörüyü ve huzuru artırır", minAge: 15, maxAge: 18 },
];


// --- Anlatım Metinleri ---
const quizSegments = [
    { segmentId: 1, narrationTitle: "Fatiha Suresi (Ayet 1-4)", narrationText: "Rahmân ve Rahîm olan Allah'ın adıyla. Hamd (Övgü ve şükür), âlemlerin Rabbi Allah’a mahsustur. O, Rahmân’dır (çok merhametlidir), Rahîm’dir (merhameti süreklidir). Hesap ve ceza gününün (din gününün) sahibidir." },
    { segmentId: 2, narrationTitle: "Hadis-i Şerif (Ameller Niyetlere Göredir)", narrationText: "Peygamber Efendimiz sallallahu aleyhi ve sellem şöyle buyurmuştur: Yapılan işler (ameller) niyetlere göre değerlenir. Herkes yaptığı işin karşılığını niyetine göre alır. Kimin niyeti Allah'a ve Resûlü'ne varmak (onların rızasını kazanmak) ise, onun hicreti (yönelişi) Allah'a ve Resûlü'nedir. Kim de elde edeceği bir dünyalığa veya evleneceği bir kadına kavuşmak için yola çıkmışsa, onun hicreti de sadece niyet ettiği o şeyedir." },
    { segmentId: 3, narrationTitle: "İhlas Suresi", narrationText: "Rahmân ve Rahîm olan Allah'ın adıyla. De ki: O Allah birdir (Ahad). Allah Samed'dir (Her şey O'na muhtaçtır, O hiçbir şeye muhtaç değildir). O, doğurmamış ve doğurulmamıştır. Hiçbir şey O'na denk ve benzer değildir." },
    { segmentId: 4, narrationTitle: "Sabrın Önemi", narrationText: "Sabır, imanın yarısıdır, denilmiştir. Sabır; başa gelen zorluklar ve sıkıntılar karşısında direnç göstermek, şikayet etmemek, aceleci davranmamak ve güzel bir şekilde Allah'tan yardım dileyerek sonucu beklemektir. Allah, sabredenlerle beraberdir ve onları mükafatlandıracaktır. Unutmayın, Kuran'da buyrulduğu gibi: Şüphesiz her zorlukla beraber bir kolaylık vardır." }
];
