# Decap CMS Yapılandırma Dosyası (Düzeltilmiş Yapı - Tekrar file: anahtarıyla)

backend:
  name: github
  repo: srgulbay/kimramazanamcaolmakister # Doğru repo adı ve kullanıcı adı
  branch: main # veya master (Repo ana dalı)
  # GitHub kimlik doğrulama ayarları (Gerekirse daha sonra bakılır)

media_folder: "" # Kullanmıyoruz
public_folder: "" # Kullanmıyoruz

collections:
  - name: "soru_bankasi"          # Koleksiyonun iç adı
    label: "Soru Bankası"          # Yönetim panelinde görünecek başlık
    file: "questions.json"       # Düzenlenecek TEK dosya
    description: "Kategorilere göre soruları buradan düzenleyebilirsiniz."
    # 'files' veya 'folder' yok, doğrudan 'file' kullandık.
    fields: # Bu dosyanın içindeki DÜZENLENEBİLİR anahtar-değer çiftleri
      - label: "Betül Soruları (8. Sınıf)"
        name: "betul"           # questions.json içindeki anahtar ("betul")
        widget: "list"          # Bu anahtarın değeri bir liste []
        label_singular: "Soru (Betül)" # Listeye eklenen tekil öğenin adı
        # Bu listedeki her bir öğenin (sorunun) alanları:
        fields:
          - { label: "Soru Metni", name: "question", widget: "text" }
          - { label: "Seçenek A", name: "optionA", widget: "string" }
          - { label: "Seçenek B", name: "optionB", widget: "string" }
          - { label: "Seçenek C", name: "optionC", widget: "string" }
          - { label: "Seçenek D", name: "optionD", widget: "string" }
          - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }

      - label: "Beyza Soruları (3. Sınıf)"
        name: "beyza"           # questions.json içindeki anahtar ("beyza")
        widget: "list"
        label_singular: "Soru (Beyza)"
        fields: # Aynı alanlar
          - { label: "Soru Metni", name: "question", widget: "text" }
          - { label: "Seçenek A", name: "optionA", widget: "string" }
          - { label: "Seçenek B", name: "optionB", widget: "string" }
          - { label: "Seçenek C", name: "optionC", widget: "string" }
          - { label: "Seçenek D", name: "optionD", widget: "string" }
          - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }

      - label: "Rümeysa Soruları (1. Sınıf)"
        name: "rumeysa"         # questions.json içindeki anahtar ("rumeysa")
        widget: "list"
        label_singular: "Soru (Rümeysa)"
        fields: # Aynı alanlar
          - { label: "Soru Metni", name: "question", widget: "text" }
          - { label: "Seçenek A", name: "optionA", widget: "string" }
          - { label: "Seçenek B", name: "optionB", widget: "string" }
          - { label: "Seçenek C", name: "optionC", widget: "string" }
          - { label: "Seçenek D", name: "optionD", widget: "string" }
          - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }

      - label: "OKS Fen Soruları"
        name: "oks_fen"         # questions.json içindeki anahtar ("oks_fen")
        widget: "list"
        label_singular: "Soru (OKS Fen)"
        fields: # Aynı alanlar
          - { label: "Soru Metni", name: "question", widget: "text" }
          - { label: "Seçenek A", name: "optionA", widget: "string" }
          - { label: "Seçenek B", name: "optionB", widget: "string" }
          - { label: "Seçenek C", name: "optionC", widget: "string" }
          - { label: "Seçenek D", name: "optionD", widget: "string" }
          - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }
