# Decap CMS Yapılandırma Dosyası (Düzeltilmiş Yapı)

backend:
  name: github
  repo: srgulbay/kimramazanamcaolmakister # Doğru repo adı
  branch: main # VEYA 'master' (Senin reponda hangisi ana dalsa onu yaz)
  # GitHub ile kimlik doğrulama ayarları (Gerekirse daha sonra bakılır)

media_folder: ""
public_folder: ""

collections:
  - name: "soru_bankasi_collection"   # Koleksiyonun iç adı
    label: "Soru Bankası Yönetimi"     # Yönetim panelinde görünecek başlık
    description: "Kategorilere göre soruları ekleyin veya düzenleyin."
    # 'file' yerine 'files' kullanıyoruz ve tek bir dosya listeliyoruz:
    files:                           # 'files' anahtarı (çoğul)
      - name: "tum_sorular"          # Bu dosya girişinin iç adı
        label: "Tüm Soruları Düzenle" # Yönetim panelinde bu dosya için görünecek etiket
        file: "questions.json"       # Düzenlenecek dosyanın yolu
        format: "json"               # Dosya formatı
        fields: # questions.json dosyasının içindeki anahtar-değerleri tanımlıyoruz
          - label: "Betül Soruları (8. Sınıf)"
            name: "betul"             # questions.json içindeki anahtar
            widget: "list"            # Bu bir liste olacak (soru listesi)
            label_singular: "Soru (Betül)" # Listeye eklenecek tekil öğe adı
            # Tekrarlanan alan tanımları (Bir önceki kodla aynı)
            fields:
              - { label: "Soru Metni", name: "question", widget: "text" }
              - { label: "Seçenek A", name: "optionA", widget: "string" }
              - { label: "Seçenek B", name: "optionB", widget: "string" }
              - { label: "Seçenek C", name: "optionC", widget: "string" }
              - { label: "Seçenek D", name: "optionD", widget: "string" }
              - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }

          - label: "Beyza Soruları (3. Sınıf)"
            name: "beyza"
            widget: "list"
            label_singular: "Soru (Beyza)"
            fields: # Alanları tekrar tanımla
              - { label: "Soru Metni", name: "question", widget: "text" }
              - { label: "Seçenek A", name: "optionA", widget: "string" }
              - { label: "Seçenek B", name: "optionB", widget: "string" }
              - { label: "Seçenek C", name: "optionC", widget: "string" }
              - { label: "Seçenek D", name: "optionD", widget: "string" }
              - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }

          - label: "Rümeysa Soruları (1. Sınıf)"
            name: "rumeysa"
            widget: "list"
            label_singular: "Soru (Rümeysa)"
            fields: # Alanları tekrar tanımla
              - { label: "Soru Metni", name: "question", widget: "text" }
              - { label: "Seçenek A", name: "optionA", widget: "string" }
              - { label: "Seçenek B", name: "optionB", widget: "string" }
              - { label: "Seçenek C", name: "optionC", widget: "string" }
              - { label: "Seçenek D", name: "optionD", widget: "string" }
              - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }

          - label: "OKS Fen Soruları"
            name: "oks_fen"
            widget: "list"
            label_singular: "Soru (OKS Fen)"
            fields: # Alanları tekrar tanımla
              - { label: "Soru Metni", name: "question", widget: "text" }
              - { label: "Seçenek A", name: "optionA", widget: "string" }
              - { label: "Seçenek B", name: "optionB", widget: "string" }
              - { label: "Seçenek C", name: "optionC", widget: "string" }
              - { label: "Seçenek D", name: "optionD", widget: "string" }
              - { label: "Doğru Cevap", name: "answer", widget: "select", options: ["A", "B", "C", "D"] }
